global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'my-ocr-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:9000']
        labels:
          service: 'api'
          env: 'compose'

